FROM node:16-alpine

ARG ENV_FILE=${ENV_FILE}
ENV ENV_FILE=${ENV_FILE}
ENV PORT=3000

# Set up folder
WORKDIR /app
COPY package.json /app
COPY package-lock.json /app
RUN npm ci --ignore-scripts

# Build
COPY . /app
RUN echo $ENV_FILE | sed 's/\\n/\n/g' > /app/.env.production \
    && npm run build

EXPOSE 3000
CMD ["npm", "start"]
