FROM node:16-alpine

ARG ENVFILE=${ENV_FILE}
ENV PORT=3000

# Set up folder
WORKDIR /app
COPY package.json /app
COPY package-lock.json /app
RUN npm ci --ignore-scripts

# Build
COPY . /app
RUN echo $ENVFILE > /app/.env.production \
    && npm run build

EXPOSE 3000
CMD ["npm", "start"]
