#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changed_files="$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)"

echo "$changed_files" | grep -E --quiet "package-lock.json" && eval "npm i"
exit 0